// Emits the 25 print QR codes (23 chapters, home ×2) as SVG to /qr, plus a contact
// sheet. Error correction M, quiet zone 4 modules. Print at ≥ 0.75 in (19 mm) with the
// URL in small type beneath (SPEC.md §6). Re-run after setting `domain` in site.config.mjs.
import QRCode from 'qrcode';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import site from '../site.config.mjs';

const root = resolve(import.meta.dirname, '..');
const out = resolve(root, 'qr');
mkdirSync(out, { recursive: true });

const domain = site.domain.replace(/\/$/, '');
if (/example/.test(domain)) {
  console.warn('⚠  site.config.mjs domain is still a placeholder (' + domain + '). Codes will be regenerated when it is set.');
}

const targets = [
  { file: 'home-back-cover', url: `${domain}/`, label: 'Back cover' },
  { file: 'home-copyright-page', url: `${domain}/`, label: 'Copyright page' },
  ...Array.from({ length: 23 }, (_, i) => ({ file: `ch-${String(i + 1).padStart(2, '0')}`, url: `${domain}/ch/${i + 1}/`, label: `Chapter ${i + 1}` })),
];

const rows = [];
for (const t of targets) {
  const svg = await QRCode.toString(t.url, { type: 'svg', errorCorrectionLevel: 'M', margin: 4, color: { dark: '#000000', light: '#ffffff' } });
  writeFileSync(resolve(out, `${t.file}.svg`), svg);
  rows.push(t);
}

const sheet = `<!doctype html><meta charset="utf-8"><title>QR contact sheet — ${site.title}</title>
<style>body{font:14px/1.4 system-ui;margin:24px}h1{font-size:18px}.g{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:24px}
figure{margin:0;text-align:center}img{width:19mm;height:19mm}figcaption{font-size:11px}code{font-size:10px;word-break:break-all}@media print{.g{gap:12px}}</style>
<h1>${site.title} — QR codes (${domain})</h1>
<p>Each code is an SVG in this folder. Print at 19 mm (0.75 in) or larger with the URL beneath. Chapter paths are a print contract and never change.</p>
<div class="g">${rows.map((r) => `<figure><img src="${r.file}.svg" alt=""><figcaption><strong>${r.label}</strong><br><code>${r.url}</code></figcaption></figure>`).join('')}</div>`;
writeFileSync(resolve(out, 'index.html'), sheet);
writeFileSync(
  resolve(out, 'README.md'),
  `# QR codes\n\nGenerated by \`npm run qr\` from \`site.config.mjs\` (domain: ${domain}).\n\n| File | Target | Placement |\n|---|---|---|\n${rows.map((r) => `| ${r.file}.svg | ${r.url} | ${r.label} |`).join('\n')}\n\nPrint spec: SVG, error correction M, quiet zone 4 modules, ≥ 19 mm square, URL printed beneath.\n`,
);
console.log(`✓ ${rows.length} QR codes → qr/ (open qr/index.html for a contact sheet)`);
